---
## Yaml file for the Automatic Mail Generation for Sending marks via Email 

### -- EXCEL FILE PARAMETERS ------ ####
inputFileName: "DA203_Score.xlsx"
masterMarkSheetName: "MainSheet"
columnStart: 1 ## Ignoring S.No
columnsEnd: 33  ## use the Excel column indicator for giving the number of last column
                ## If not intrested in counting, Give a sufficiently larger number like 50
nRows: 77    ## Exact Number of Students
HeaderEmail: "Email ID"  ## Column header which stores email id
HeaderName: "Name"       ## Column header which stores names
skipRows: 2  ## Number of rows before the Header row in excel ( "Email", "Marks")


## -- Jinja File Templates --- ##
## -- The contents will appear inside the PDF as requested -- ##
jinjaTemplateFileName : "template.html"


SubjectName: "DA203-O - Introduction to computing for AI and ML"

instructionArray:
- IMPORTANT- The mark summary is just for your information only, the final grades and marks for this course will be ones which appear on your transcript."""
- Penalty have been added to PSet in case of late submission 
- Kindly do not share the document with others and do not bring any queries regarding marks interms of comparision with other's mark
- Do not reply to this email for any clarifications(as it is an autogenerated email)

### --------- Section -1 -------------------- ###

## Enter the Heading for Section-1 Table 
section-1-Heading:
- "Item"
- "MaxMarks"
- "MarksObtained"
- "ScaledTo"
- "MarksObtained(Scalled)"

## Enter Column Headers for Actual Marks Scored "Columns" and the total Marks 
ActualMarks:
  "Pset-1" : 50
  "Pset-2" : 60
  "Pset-3" : 60
  "Quiz1" : 100
  "Quiz2" : 17
  "Quiz3" : 12
  "Quiz4" : 10
  "Quiz5" : 30
  "MidTerm" : 40
  "EndTerm" : 60


NormalisedMarks:
   "Pset-1 (N)" : 12.5
   "Pset-2 (N)" : 12.5
   "Pset-3 (N)" : 12.5
   "Quiz1 (N)" : 5
   "Quiz2 (N)" : 5
   "Quiz3 (N)": 5
   "Quiz4 (N)" : 5
   "Quiz5 (N)" : 5
   "MidTerm (N)": 20
   "EndTerm (N)" : 20




### --------- Section -2 FINAL SUMMARY SECTION -------------------- ###
## This is for final display of all consolidated columns into the main mark section ( out of 100 )

## Change this to true, if you want to print the second section
section-2-Needed: true

section-2-Heading:
- "Item"
- "MaxMarks"
- "MarksObtained"

## FInal list of Marks that you want to Display ( Column Headers )
section-2-marks:
  "MidTerm (N)" : 20
  "BEST QUIZ" : 20
  "BEST_PSET" : 25
  "EndTerm (N)" : 20

## -- Section 3 - Send Email with pdf attachment to the corresponding people -- ##
sendEmail: False

EmailSubject: "DA-203(0)- Marks Summary - [Do not Reply back] - AutoGenerated Mail"
cc:
- xyz@abc.co.in
- ttg@great.com

emailSMTPSender: 'noreplystars.cds@auto.iisc.ac.in'
emailSMTPPassword: xxxxxxxxxxxxxxxxxxxxxx

## Seconds to Sleep before sending consecutive mails
## Strictly usefull for stopping bad emails on time
sleepTime: 1
