---
## Yaml file for the Automatic Mail Generation for Sending marks via Email 

### -- EXCEL FILE PARAMETERS ------ ####
inputFileName: "Scoring Sheet.xlsx"
masterMarkSheetName: "MainSheet"
columnStart: 1 ## Ignoring S.No
columnsEnd: 33  ## use the Excel column indicator for giving the number of last column
                ## If not intrested in counting, Give a sufficiently larger number like 50
nRows: 61    ## Exact Number of Students
HeaderEmail: "Email ID"  ## Column header which stores email id
HeaderName: "Name"       ## Column header which stores names
skipRows: 2  ## Number of rows before the Header row in excel ( "Email", "Marks")


## -- Jinja File Templates --- ##
jinjaTemplateFileName : "template.html"


### --------- Section -1 -------------------- ###

## Enter the Heading for Section-1 Table 
section-1-Heading:
- "Item"
- "MaxMarks"
- "MarksObtained"
- "ScaledTo"
- "MarksObtained(Scalled)"

## Enter Column Headers for Actual Marks Scored "Columns" and the total Marks 
ActualMarks:
  "Problem_set-1" : 40
  "Problem_set-2" : 50
  "Quiz-1" : 10
  "Quiz-2" : 10
  "Quiz-3" : 10
  "Midterm" : 60
  "Quiz-4" : 10
  "Quiz-5" : 10
  "Quiz-Final" : 10
  "Problem_set-3" : 35
  "Problem_set-4" : 100
  "Final Exam":   50
  "Project": 100

NormalisedMarks:
   "Problem_set-1_Normalized" : 8
   "Problem_set-2_Normalized" : 8
   "Quiz1-Normalised" : 5
   "Quiz2-Normalised" : 5
   "Quiz3-Normalised" : 5
   "Midterm-Normalised": 18
   "Quiz4-Normalised" : 5
   "Quiz5-Normalised" : 5
   "QuizFinal-Normalised": 5
   "Pset3-Normalised" : 8
   "Pset4-Normalised" : 8
   "Final Exam-Normalised": 18
   "Project-Normalised" : 20




### --------- Section -2 FINAL SUMMARY SECTION -------------------- ###
## This is for final display of all consolidated columns into the main mark section ( out of 100 )

## Change this to true, if you want to print the second section
section-2-Needed: true

section-2-Heading:
- "Item"
- "MaxMarks"
- "MarksObtained"

## FInal list of Marks that you want to Display ( Column Headers )
section-2-marks:
  "Midterm-Normalised" : 18
  "BEST QUIZ" : 20
  "QuizFinal-Normalised" : 5
  "BEST PSET" : 24
  "BONUS" : 5
  "Final Exam-Normalised" : 18

## -- Section 3 - Send Email with pdf attachment to the corresponding people -- ##
sendEmail: false

EmailSubject: "CCE-2022 - Marks Summary - [Do not Reply back] - AutoGenerated Mail"
cc:
- abc@gmail.comas
- abc@gmail.comas
- abc@gmail.comas

## Seconds to Sleep before sending consecutive mails
## Strictly usefull for stopping bad emails on time
sleepTime: 5
